language: go

go:
  - 1.9.2

install:
  - ./scripts/install-dependencies.sh
  - dep ensure

script:
  - gometalinter --vendor ./...
  - go test -race -covermode=atomic -coverprofile=coverage.txt
  - goveralls -covermode=atomic -coverprofile=coverage.txt

after_success:
