language: go

go:
  - 1.9.2

install:
  - ./scripts/install-dependencies.sh
  - make dep

script:
  - make linter
  - make test

after_success:
  - goveralls -v -race -covermode=atomic -service=travis-ci
