version: '3.2'

services:
  test:
    image: warp-pipe/golang:1.9.2-stretch
    volumes:
      - type: bind
        source: .
        target: /go/src/github.com/pagarme/warp-pipe
      - type: bind
        source: ${GOPATH}/pkg/linux_amd64
        target: /go/pkg/linux_amd64
    working_dir: /go/src/github.com/pagarme/warp-pipe
    command: go test -v ./...
