
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.14.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/docker/docker"
  version = "=17.5.0-ce"

# https://github.com/moby/moby/blob/v17.05.0-ce/vendor.conf#L48
[[override]]
  name = "github.com/docker/distribution"
  revision = "b38e5838b7b2f2ad48e06ec4b500011976080621"

[[constraint]]
  name = "github.com/jackc/pgx"
  version = "3.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/looplab/fsm"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.7.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"
