version: '3'

services:
  golang:
    image: warp-pipe/golang:1.9.2-stretch
    build: golang:1.9.2-stretch
  postgres-client:
    image: warp-pipe/postgres-client:9.5-stretch-slim
    build: postgres-client:9.5-stretch-slim
  postgres-server:
    image: warp-pipe/postgres-server:9.5.6
    build: postgres-server:9.5.6
