version: '3'

services:
  golang:
    image: warp-pipe/golang:1.9.2-stretch
    build:
      dockerfile: docker/base-images/golang:1.9.2-stretch/Dockerfile
      context: ../..
  postgres-client:
    image: warp-pipe/postgres-client:9.5-stretch-slim
    build:
      dockerfile: docker/base-images/postgres-client:9.5-stretch-slim/Dockerfile
      context: ../..
  postgres-server:
    image: warp-pipe/postgres-server:9.5.6
    build:
      dockerfile: docker/base-images/postgres-server:9.5.6/Dockerfile
      context: ../..
